import Navbar from "@/app/components/Navbar";

export const metadata = {
  title: 'Products',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <>
      <Navbar/>
      {children}
    </>
  )
}
