import ProductsNavbar from "@/app/(pages)/products/components/ProductsNavbar";

export const metadata = {
  title: 'Products',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <>
      <ProductsNavbar/>
      {children}
    </>
  )
}
